#!/usr/bin/env python3
"""Inventory of the two ECCO v4r4 override trees against MITgcm checkpoint66g.

For every file in `code/` (full V4r4) and `flux-forced/code/` it finds the c66g file it replaces and
counts changed lines, both raw and with Fortran comments and blank lines removed ("code" lines). It also
compares the two trees with each other.

    audit_overrides.py                 print the inventory and CPP tables (markdown)
    audit_overrides.py --update FILE   rewrite the two generated sections of FILE in place
    audit_overrides.py --check FILE    exit 1 unless FILE (docs/OVERRIDES.md) holds exactly the current
                                       inventory and CPP tables AND a classification row for every changed file

The inventory in docs/OVERRIDES.md sits between the markers below and is generated, never hand-edited.
The classification table (`| \\`name\\` | ... |` rows under "## Classification") is hand-written.
"""

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
C66G = REPO / "MITgcm_c66g"
V4R4 = REPO / "ECCO-v4-Configurations" / "ECCOv4 Release 4"
TREES = {"full": V4R4 / "code", "ff": V4R4 / "flux-forced" / "code"}

BEGIN = "<!-- BEGIN INVENTORY (generated by scripts/audit_overrides.py; do not edit) -->"
END = "<!-- END INVENTORY -->"
CPP_BEGIN = "<!-- BEGIN CPP (generated by scripts/audit_overrides.py; do not edit) -->"
CPP_END = "<!-- END CPP -->"

# Build-machine files and TAF lists: not source overrides of c66g.
NOT_SOURCE = {"CVS", "linux_amd64_ifort+mpi_ice_nas", "linux_ifort_impi_aws_sysmodule", "code_ad_diff.list"}
# Where a same-named file in c66g is the one used by genmake2 for this build. Searched in order;
# verification/, utils/, tools/ and packages V4r4 does not compile are never the base.
SEARCH = ["model/inc", "model/src", "eesupp/inc", "eesupp/src", "pkg"]
NOT_BASE_PKGS = {"openad", "atm_ocn_coupler"}


def find_base(name, c66g=C66G):
    hits = []
    for d in SEARCH:
        root = c66g / d
        for p in sorted(root.rglob(name)):
            if d == "pkg" and p.relative_to(root).parts[0] in NOT_BASE_PKGS:
                continue
            hits.append(p)
        if hits:
            break
    if len(hits) > 1:
        raise RuntimeError(f"ambiguous c66g base for {name}: {hits}")
    return hits[0] if hits else None


_COMMENT = re.compile(r"^([cC*!]|\s*!)")


def code_lines(text, fortran):
    """Lines that are not blank and (for Fortran/headers) not comments; trailing blanks stripped."""
    out = []
    for line in text.splitlines():
        s = line.rstrip()
        if not s.strip():
            continue
        if fortran and _COMMENT.match(s):
            continue
        out.append(s)
    return out


def ndiff(a, b):
    """Number of changed lines (inserted + deleted) between two line lists."""
    n = 0
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
        if tag != "equal":
            n += (i2 - i1) + (j2 - j1)
    return n


def _read(p):
    return p.read_text(errors="replace")


def compare(a_path, b_path):
    """(raw changed lines, code changed lines) between two files."""
    ta, tb = _read(a_path), _read(b_path)
    fortran = a_path.suffix in (".F", ".h")
    return ndiff(ta.splitlines(), tb.splitlines()), ndiff(code_lines(ta, fortran), code_lines(tb, fortran))


def inventory(trees=None, c66g=C66G):
    trees = TREES if trees is None else trees
    names = sorted({p.name for t in trees.values() for p in t.iterdir()} - NOT_SOURCE, key=str.lower)
    rows = []
    for name in names:
        row = {"name": name}
        base = find_base(name, c66g)
        row["base"] = base.relative_to(c66g).as_posix() if base else None
        for key, tdir in trees.items():
            p = tdir / name
            if not p.exists():
                row[key] = None
            elif base is None:
                row[key] = "new"
            else:
                raw, code = compare(base, p)
                row[key] = (raw, code)
        pf, pff = trees["full"] / name, trees["ff"] / name
        if pf.exists() and pff.exists():
            row["full_vs_ff"] = compare(pf, pff)
        else:
            row["full_vs_ff"] = None
        rows.append(row)
    return rows


def changed_files(rows):
    """Names that differ from c66g in at least one tree, or are new."""
    out = []
    for r in rows:
        for key in ("full", "ff"):
            v = r[key]
            if v == "new" or (isinstance(v, tuple) and v[0] > 0):
                out.append(r["name"])
                break
    return out


def _cell(v):
    if v is None:
        return "—"
    if v == "new":
        return "new"
    raw, code = v
    return "identical" if raw == 0 else f"{code} ({raw})"


def render(rows):
    lines = [BEGIN,
             "| file | c66g base | full vs c66g | flux-forced vs c66g | full vs flux-forced |",
             "|---|---|---|---|---|"]
    for r in rows:
        base = f"`{r['base']}`" if r["base"] else "—"
        lines.append(f"| `{r['name']}` | {base} | {_cell(r['full'])} | {_cell(r['ff'])} | "
                     f"{_cell(r['full_vs_ff'])} |")
    lines.append(END)
    return "\n".join(lines)


_CPP_LINE = re.compile(r"^\s*#\s*(define|undef|ifdef|ifndef|if|elif|else|endif)\b\s*(.*)$")


def cpp_macros(text):
    """{macro: [(state, context)]} for every #define/#undef line; context = enclosing #if conditions
    ('!' marks an #else branch). Fortran comment lines (C#define, c#undef) are not CPP and are skipped."""
    out, stack = {}, []
    for line in text.splitlines():
        m = _CPP_LINE.match(line)
        if not m:
            continue
        kw, rest = m.group(1), m.group(2).split("/*")[0].strip()
        if kw in ("define", "undef"):
            name = rest.split()[0] if rest.split() else ""
            if name and not name.endswith("_H"):
                out.setdefault(name, []).append((kw, " & ".join(stack)))
        elif kw == "ifdef":
            stack.append(rest.split()[0])
        elif kw == "ifndef":
            stack.append("!" + rest.split()[0])
        elif kw == "if":
            stack.append(re.sub(r"\s+", " ", rest))
        elif kw in ("elif", "else") and stack:
            stack[-1] = "!(" + stack[-1] + ")" + (f" & {rest}" if kw == "elif" else "")
        elif kw == "endif" and stack:
            stack.pop()
    return out


def _context(ctx):
    """Drop include guards (`!X_H`, `!(ECCO_CPPOPTIONS_H)`) and the package's own leading ALLOW_<PKG> guard."""
    conds = [c for c in ctx.split(" & ") if c and not re.fullmatch(r"!\(?\w+_H\)?", c)]
    if conds and re.fullmatch(r"ALLOW_\w+", conds[0]):
        conds = conds[1:]
    return " & ".join(conds)


def _state(entries):
    if entries is None:
        return "absent"
    return "; ".join(s + (f" [if {_context(c)}]" if _context(c) else "") for s, c in entries)


def cpp_rows(trees=None, c66g=C66G):
    """Macros whose state differs between c66g, full and flux-forced, per options header that either
    tree overrides. Rows: (header, macro, c66g, full, ff)."""
    trees = TREES if trees is None else trees
    headers = sorted({p.name for t in trees.values() for p in t.glob("*OPTIONS.h")}, key=str.lower)
    rows = []
    for h in headers:
        base = find_base(h, c66g)
        srcs = [base] + [trees[k] / h for k in ("full", "ff")]
        # A tree without its own copy compiles the c66g header.
        texts = [(_read(p) if p is not None and p.exists() else (_read(base) if base else "")) for p in srcs]
        maps = [cpp_macros(t) for t in texts]
        for name in sorted(set().union(*maps), key=str.lower):
            states = [_state(m.get(name)) for m in maps]
            if len(set(states)) > 1:
                rows.append((h, name, *states))
    return rows


def render_cpp(rows):
    lines = [CPP_BEGIN,
             "| header | macro | c66g | full | flux-forced |",
             "|---|---|---|---|---|"]
    for h, name, a, b, c in rows:
        lines.append(f"| `{h}` | `{name}` | {a} | {b} | {c} |")
    lines.append(CPP_END)
    return "\n".join(lines)


def _section(doc_text, begin, end):
    if begin not in doc_text or end not in doc_text:
        return None
    return doc_text[doc_text.index(begin):doc_text.index(end) + len(end)]


_CLASS_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|")


def classified(doc_text):
    """File names in the hand-written classification table."""
    if "## Classification" not in doc_text:
        return set()
    section = doc_text.split("## Classification", 1)[1].split("\n## ", 1)[0]
    return {m.group(1) for line in section.splitlines() if (m := _CLASS_ROW.match(line))}


def check(doc_text, rows, crows=None):
    """Return a list of problems (empty = docs/OVERRIDES.md is complete and current)."""
    problems = []
    for what, begin, end, table in (("inventory", BEGIN, END, render(rows)),
                                    ("CPP", CPP_BEGIN, CPP_END, render_cpp(crows or []))):
        current = _section(doc_text, begin, end)
        if current is None:
            problems.append(f"{what} markers missing")
        elif current != table:
            problems.append(f"{what} table is stale: regenerate with scripts/audit_overrides.py")
    want, have = set(changed_files(rows)), classified(doc_text)
    if want - have:
        problems.append(f"changed files without a classification row: {sorted(want - have)}")
    if have - want:
        problems.append(f"classification rows for files that are not changed: {sorted(have - want)}")
    return problems


def update(doc_text, rows, crows):
    """doc_text with both generated sections replaced by the current tables (markers must exist)."""
    for begin, end, table in ((BEGIN, END, render(rows)), (CPP_BEGIN, CPP_END, render_cpp(crows))):
        old = _section(doc_text, begin, end)
        if old is None:
            raise SystemExit(f"markers missing: {begin}")
        doc_text = doc_text.replace(old, table)
    return doc_text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", metavar="FILE")
    g.add_argument("--update", metavar="FILE")
    args = ap.parse_args(argv)
    rows, crows = inventory(), cpp_rows()
    if args.update:
        path = Path(args.update)
        path.write_text(update(path.read_text(), rows, crows))
        print(f"updated {path}")
        return 0
    if not args.check:
        print(render(rows))
        print()
        print(render_cpp(crows))
        return 0
    problems = check(Path(args.check).read_text(), rows, crows)
    for p in problems:
        print("FAIL:", p)
    if not problems:
        print(f"OK: {len(rows)} files, {len(changed_files(rows))} changed, all classified")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
