"""exch2 halo exchanges as one gather per call (plan Task 7; single-device path).

The halo maps are the Fortran exchanges themselves: `reference/jaxdump/jaxdump.F` (JAXDUMP_EXCH_PROBE) fills every
tile interior with an exact code (1e6*component + 1e4*tile + 100*j + i), zero halos, calls each exch2 exchange routine
the model uses, and dumps the result with halos. Decoding a halo value gives its source point, source component (u or
v array: vector exchanges swap components across rotated facet edges) and sign; 0 means "not written by the exchange"
(the point keeps its previous value, as in Fortran). `build_maps()` turns a probe dump into `ExchangeMaps`
(`mitgcm_jax/data/exch_maps_<layout>.npz`, generated by `scripts/make_exch_maps.py`).

Kinds (Fortran routine -> probe fields):
    T     EXCH_XY_RL / EXCH_XYZ_RL / EXCH_3D_RL (scalar)       xT (x3D must be identical)
    UVs   EXCH_UV_XY_RL(u, v, .TRUE.)  (C-grid vector, signs)  xUVs_u, xUVs_v   (also EXCH_UV_XYZ_RL, EXCH_UV_3D_RL)
    UVn   EXCH_UV_XY_RL(u, v, .FALSE.)                         xUVn_u, xUVn_v
    Z     EXCH_Z_3D_RL (vorticity points)                      xZ
    As/An EXCH_UV_AGRID_3D_RL(u, v, signs)                     xAs_*, xAn_*
    Bs/Bn EXCH_UV_BGRID_3D_RL(u, v, signs)                     xBs_*, xBn_*
    SMs   EXCH_SM_3D_RL(phi, .TRUE.)                           xSMs
    Ds    EXCH_UV_DGRID_3D_RL(u, v, .TRUE.)                    xDs_u, xDs_v

An exchange is linear (copy with sign), so its JAX transpose is the matching scatter-add: gradients need nothing extra.
"""

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import jax.numpy as jnp

from mitgcm_jax.layout import Layout

MAP_DIR = Path(__file__).resolve().parents[1] / "data"

SCALAR_KINDS = {"T": "xT", "3D": "x3D", "Z": "xZ", "SMs": "xSMs"}
VECTOR_KINDS = {"UVs": ("xUVs_u", "xUVs_v"), "UVn": ("xUVn_u", "xUVn_v"), "As": ("xAs_u", "xAs_v"),
                "An": ("xAn_u", "xAn_v"), "Bs": ("xBs_u", "xBs_v"), "Bn": ("xBn_u", "xBn_v"),
                "Ds": ("xDs_u", "xDs_v"), "UV3s": ("xUV3s_u", "xUV3s_v")}


def decode(probe, layout):
    """probe: [T, ny, nx] exchanged code field -> (src flat index, comp 0/1/2, sign +-1), each [T*ny*nx].
    comp 0 = keep own value (interior point, or halo point the exchange does not write)."""
    L = layout
    T, ny, nx = probe.shape
    assert (T, ny, nx) == L.shape2d, (probe.shape, L.shape2d)
    own = np.arange(T * ny * nx, dtype=np.int64).reshape(T, ny, nx)
    v = np.rint(probe).astype(np.int64)
    if not np.array_equal(v, probe):
        raise ValueError("probe values are not integers")
    a = np.abs(v)
    comp = a // 1000000
    tile = (a % 1000000) // 10000
    j = (a % 10000) // 100
    i = a % 100
    sign = np.where(v < 0, -1, 1)
    src = ((tile - 1) * ny + (j - 1 + L.OLy)) * nx + (i - 1 + L.OLx)
    src = np.where(comp > 0, src, own)
    # interior points must hold their own code (an exchange never writes the interior); they map to themselves
    ti, jj, ii = np.meshgrid(np.arange(T), np.arange(ny), np.arange(nx), indexing="ij")
    interior = ((jj >= L.OLy) & (jj < L.OLy + L.sNy) & (ii >= L.OLx) & (ii < L.OLx + L.sNx))
    if not (np.all(src[interior] == own[interior]) and np.all(sign[interior] == 1)):
        raise ValueError("the exchange changed an interior point")
    comp = np.where(interior, 0, comp)
    return src.reshape(-1), comp.reshape(-1).astype(np.int8), sign.reshape(-1).astype(np.int8), interior.reshape(-1)


@dataclass(frozen=True)
class ExchangeMaps:
    layout: Layout
    maps: dict  # name -> (src int32[N], comp int8[N], sign float64[N]); vector kinds have name+'_u', name+'_v'

    def save(self, path):
        arrs = {}
        for k, (s, c, g) in self.maps.items():
            arrs[k + ".src"], arrs[k + ".comp"], arrs[k + ".sign"] = s, c, g.astype(np.int8)
        L = self.layout
        arrs["layout"] = np.array([L.sNx, L.sNy, L.OLx, L.OLy, L.nTiles, L.Nr])
        np.savez_compressed(path, **arrs)

    @classmethod
    def load(cls, path):
        z = np.load(path)
        sNx, sNy, OLx, OLy, nT, Nr = (int(x) for x in z["layout"])
        L = Layout(sNx, sNy, OLx, OLy, nT, Nr)
        names = sorted({k.rsplit(".", 1)[0] for k in z.files if k != "layout"})
        maps = {n: (z[n + ".src"].astype(np.int32), z[n + ".comp"], z[n + ".sign"].astype(np.float64)) for n in names}
        return cls(L, maps)


def build_maps(dumpset, it, stage="G00_geometry", layout=None):
    """ExchangeMaps from a probe dump (records xT, xUVs_u, ... at `stage`, iteration `it`)."""
    L = layout or Layout()
    maps = {}

    def field(name):
        recs = dumpset.tiles(it, stage, name)
        return np.stack([recs[t + 1].data[0] for t in range(L.nTiles)])

    for kind, name in SCALAR_KINDS.items():
        s, c, g, interior = decode(field(name), L)
        if np.any(c == 2) or (kind != "SMs" and np.any(g < 0)):  # EXCH_SM_3D with signs may flip signs
            raise ValueError(f"scalar exchange {name} took a v-component or a sign")
        maps[kind] = (s.astype(np.int32), c, g.astype(np.float64))
    for kind, (nu, nv) in VECTOR_KINDS.items():
        for suffix, name in (("_u", nu), ("_v", nv)):
            s, c, g, interior = decode(field(name), L)
            maps[kind + suffix] = (s.astype(np.int32), c, g.astype(np.float64))
    return ExchangeMaps(L, maps)


def _flat(a, L):
    """[T, ..., ny, nx] -> ([..., T*ny*nx], lead shape)"""
    a = jnp.moveaxis(a, 0, -3)
    lead = a.shape[:-3]
    return a.reshape(*lead, L.nTiles * L.ny * L.nx), lead


def _unflat(f, lead, L):
    return jnp.moveaxis(f.reshape(*lead, L.nTiles, L.ny, L.nx), -3, 0)


def _apply(m, own, fa, fb):
    """own: the output component's current values (kept where comp == 0); fa/fb: u-like / v-like sources."""
    src, comp, sign = m
    out = jnp.where(comp == 1, fa[..., src], own)
    if fb is not None:
        out = jnp.where(comp == 2, fb[..., src], out)
    return out * sign


class Exchanger:
    """Halo exchanges on [tile, ..., j, i] arrays. One code path for numpy/jax inputs (returns jax arrays)."""

    def __init__(self, maps: ExchangeMaps):
        self.L = maps.layout
        self.m = {k: (jnp.asarray(s), jnp.asarray(c), jnp.asarray(g)) for k, (s, c, g) in maps.maps.items()}

    def scalar(self, a, kind="T"):
        fa, lead = _flat(jnp.asarray(a), self.L)
        return _unflat(_apply(self.m[kind], fa, fa, None), lead, self.L)

    def vector(self, u, v, kind="UVs"):
        fu, lead = _flat(jnp.asarray(u), self.L)
        fv, _ = _flat(jnp.asarray(v), self.L)
        uo = _apply(self.m[kind + "_u"], fu, fu, fv)
        vo = _apply(self.m[kind + "_v"], fv, fu, fv)
        return _unflat(uo, lead, self.L), _unflat(vo, lead, self.L)

    # Fortran names
    def exch_xy(self, a):  # EXCH_XY_RL / EXCH_XYZ_RL / EXCH_3D_RL
        return self.scalar(a, "T")

    def exch_uv_xy(self, u, v, with_signs=True):  # EXCH_UV_XY_RL / EXCH_UV_XYZ_RL
        return self.vector(u, v, "UVs" if with_signs else "UVn")

    def exch_z(self, a):  # EXCH_Z_3D_RL
        return self.scalar(a, "Z")

    def exch_uv_agrid(self, u, v, with_signs=True):
        return self.vector(u, v, "As" if with_signs else "An")

    def exch_uv_bgrid(self, u, v, with_signs=True):
        return self.vector(u, v, "Bs" if with_signs else "Bn")


def default_exchanger(layout=None):
    L = layout or Layout()
    return Exchanger(ExchangeMaps.load(MAP_DIR / f"exch_maps_{L.nTiles}x{L.sNx}x{L.sNy}.npz"))
